import os
from smolagents import CodeAgent, LiteLLMModel
from tools import (
    search_tool, webpage_tool, 
    extract_key_facts, check_source_credibility,
    save_note, generate_citations
)

SYSTEM_PROMPT_ADDITION = """
You are an expert research agent. Given a research topic, produce a highly detailed, comprehensive research digest.

Follow this research workflow:
1. SEARCH: Perform 2 search queries using web_search to find authoritative sources (including Wikipedia, academic, news, or government sites).
2. VISIT: Use visit_webpage on 2-3 top source URLs to extract full content.
3. EXTRACT: Use extract_key_facts to extract rich, detailed bullet points from each visited page.
4. VERIFY: Use check_source_credibility to evaluate the domain credibility of each URL.
5. LOG: Use save_note to save findings into the research log.
6. CITE: Use generate_citations to compile all references.
7. SYNTHESIZE: Write an in-depth, thorough final research digest.

Your final output MUST be comprehensive and structured as follows:
- **Executive Summary**: A detailed 2-paragraph overview explaining the core topic, significance, and current state.
- **In-Depth Analysis & Key Findings**: Group findings into thematic sections with detailed explanations, technical details, statistics, and domain insights.
- **Source Credibility Evaluation**: Explicitly discuss the reliability and tier of the sources consulted.
- **References**: Clean citations block generated by generate_citations.

Do not provide brief or superficial summaries. Provide rich, thorough research.
"""

def create_agent(api_key: str = None):
    key = api_key or os.getenv("GROQ_API_KEY", "")
    if key:
        os.environ["GROQ_API_KEY"] = key
    
    model = LiteLLMModel(
        model_id="groq/llama-3.3-70b-versatile",
        api_key=key,
        temperature=0.2,
        max_tokens=4096
    )
    
    tools = [
        search_tool,
        webpage_tool,
        extract_key_facts,
        check_source_credibility,
        save_note,
        generate_citations
    ]
    
    agent = CodeAgent(
        tools=tools,
        model=model,
        max_steps=10,
        additional_authorized_imports=["re", "json", "datetime", "urllib"],
        verbosity_level=1
    )
    
    agent.prompt_templates["system_prompt"] = (
        agent.prompt_templates["system_prompt"] + SYSTEM_PROMPT_ADDITION
    )
    
    return agent
